### Project 1: Basic Data Scaling
#### Objective: Scale a 2D dataset matrix (columns are features) by subtracting the mean and dividing by the standard deviation of each feature. 
#### Technique: Use M.mean(axis=0) and M.std(axis=0) and then perform vectorized subtraction and division. 

##### Step 1. Import Numpy

In [1]:
import numpy as np

##### Step 2. Create a sample 2D dataset (rows = samples, columns = features)

In [2]:
M = np.array([
    [85, 90, 80],
    [78, 82, 76],
    [92, 88, 89],
    [70, 75, 85]
])

print("Original Matrix:\n", M)

Original Matrix:
 [[85 90 80]
 [78 82 76]
 [92 88 89]
 [70 75 85]]


##### Step 3: Calculate mean and standard deviation for each column (feature)

In [7]:
mean = M.mean(axis=0)   # Mean of each feature
std = np.round(M.std(axis=0),2)     # Standard deviation of each feature

print("\nMean of each feature:", mean)
print("Standard deviation of each feature:", std)

# axis=0 means it calculates column-wise
# mean → average of each subject
# std → how much each score varies from the mean


Mean of each feature: [81.25 83.75 82.5 ]
Standard deviation of each feature: [8.17 5.85 4.92]


##### Step 4: Scale the matrix (Z-score normalization)

In [ ]:
M_scaled = (M - mean) / std
M_scaled = np.round(M_scaled, 2)
print("\nScaled Matrix:\n", M_scaled)

# To clearly see how much above/below average each item is
# A positive value → above average
# A negative value → below average
# 0 → exactly average


Scaled Matrix:
 [[ 0.46  1.07 -0.51]
 [-0.4  -0.3  -1.32]
 [ 1.32  0.73  1.32]
 [-1.38 -1.5   0.51]]
