### Project 1: From Data to Matrix
#### Objective: Convert a raw dataset into a NumPy matrix and perform basic transformations. 

##### Step 1: Import libraries

In [1]:
import numpy as np

##### Step 2: Create Raw Data

In [3]:
# created a small dataset using a list of lists
# Each record: [name, math_score, science_score]
data = [
    ["Arjun", 85, 90],
    ["Priya", 78, 82],
    ["Sarah", 92, 88],
    ["Kavya", 70, 75]
]

##### Step 3: Convert to Matrix (numerical part only)

In [5]:
# Extract numerical scores (columns 1 and 2)
scores = np.array([row[1:] for row in data])
print("Original Matrix (Math & Science Scores):")
print(scores)

# row[1:] means row-wise we take all elements from index 1 onwards (i.e., skip the name and take only scores)
# index 0 have name we need to skip the name

Original Matrix (Math & Science Scores):
[[85 90]
 [78 82]
 [92 88]
 [70 75]]


##### Step 5: Add a New Feature (sports score) 

In [7]:
sports_score = np.array([[80], [76], [89], [85]])
scores_with_sports = np.hstack((scores, sports_score))
print("\nMatrix After Adding Sports Score:")
print(scores_with_sports)

# created a new column (sports_score) for each student
# np.hstack() horizontally stacks the arrays — after scores adds the new column sports_score to the right side


Matrix After Adding Sports Score:
[[85 90 80]
 [78 82 76]
 [92 88 89]
 [70 75 85]]


##### Step 6: Calculate New Feature (average score)

In [12]:
average_score = np.mean(scores_with_sports, axis=1).reshape(-1, 1)
scores_with_avg = np.hstack((scores_with_sports, average_score))
print("\nMatrix After Adding Average Score:")
print(scores_with_avg)

# np.mean(..., axis=1) calculates the average of each row (each student’s scores)
# axis=1 - (row-wise operation)
# axis=0 - column-wise operation
# .reshape(-1, 1) changes the 1D array into a column vector, so it can be added as a new column.
# reshape - 1 - Number of columns, -1 - NumPy will automatically figure out how many rows are needed
# np.hstack() adds that average column to the matrix


Matrix After Adding Average Score:
[[85.00 90.00 80.00 85.00]
 [78.00 82.00 76.00 78.67]
 [92.00 88.00 89.00 89.67]
 [70.00 75.00 85.00 76.67]]


##### Step 7: Scale a Feature (increase math score)

In [15]:
scaled_scores = scores_with_avg.copy()
scaled_scores[:, 0] = scaled_scores[:, 0] * 1.1  # math_score * 1.1
print("\nMatrix After Scaling Math Score (10% Increase):")
print(scaled_scores)

# .copy() makes a copy of the matrix so the original stays unchanged
# scaled_scores[:, 0] means “all rows in column 0” → the Math score column
# Multiply by 1.1 to increase Math scores by 10%


Matrix After Scaling Math Score (10% Increase):
[[ 93.50  90.00  80.00  85.00]
 [ 85.80  82.00  76.00  78.67]
 [101.20  88.00  89.00  89.67]
 [ 77.00  75.00  85.00  76.67]]


##### Step 8: Output

In [16]:
print("\nOriginal vs Transformed Matrices:")
print("Original:\n", scores)
print("\nTransformed:\n", scaled_scores)


Original vs Transformed Matrices:
Original:
 [[85 90]
 [78 82]
 [92 88]
 [70 75]]

Transformed:
 [[ 93.50  90.00  80.00  85.00]
 [ 85.80  82.00  76.00  78.67]
 [101.20  88.00  89.00  89.67]
 [ 77.00  75.00  85.00  76.67]]
