### Project 2: Simple Neural Network Layer Simulation
#### Objective: Simulate a single layer of a neural network using matrix and vector multiplication. 

##### Step 1: Import NumPy

In [2]:
import numpy as np

##### Step 2: Define Inputs (3 input features)

In [3]:
# 3 inputs → 2 outputs (so 3x2 matrix)
input_vector = np.array([2, 3, 4])
print(input_vector)

# Input Vector - Like 3 features going into a neuron

[2 3 4]


##### Step 3: Define Weights and Bias

In [4]:
# 3 inputs → 2 outputs (so 3x2 matrix)
np.random.seed(42)
weights_matrix = np.round(np.random.rand(3, 2), 3)   # random values between 0 and 1
bias_vector = np.array([0.1, 0.2])
print("Weighted Matrix:\n",weights_matrix)
print("\nBias Vector: ", bias_vector)

# np.random.seed(42) - ensures results are the same every time you run it
# weights_matrix connects 3 inputs → 2 output neurons → so its shape is (3, 2)
# Each column is one neuron’s weights
# np.random.rand() gives random numbers between 0 and 1
# Bias gives the neuron extra flexibility — it shifts the output(like adding a small adjustment value)

Weighted Matrix:
 [[0.375 0.951]
 [0.732 0.599]
 [0.156 0.156]]

Bias Vector:  [0.1 0.2]


##### Step 4: Linear Transformation (Matrix Multiplication)

In [5]:
# Formula: output = input_vector @ weights_matrix + bias_vector
# "@" is matrix multiplication
linear_output = input_vector @ weights_matrix + bias_vector
print(linear_output)

# Matrix Multiplication - Combines all weighted inputs + bias to form the "raw output"
# output=(inputs × weights)+bias
# output_neuron1 = (2*w1) + (3*w2) + (4*w3) + bias1
# output_neuron2 = (2*w1) + (3*w2) + (4*w3) + bias2



[3.67  4.523]


##### Step 5: Add Activation Function (Sigmoid)

In [6]:
# Sigmoid squashes values between 0 and 1
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
# Apply Activation
activated_output = np.round(sigmoid(linear_output), 3)
print("Linear Output:", linear_output)
print("Activated Output:", activated_output)

# Sigmoid Activation - This function compresses the value into a range between 0 and 1
#  σ(x)= 1 / (1+e^−x) - x = input value, e = ≈ 2.71828 Eulers number
# np.exp - exponential - when x is positive, e^−x becomes very small, when x is negative, e^-x becomes large
# the reciprocal (1 divided by the sum) - This forces the output to always stay between 0 and 1
# Negative inputs → close to 0, Positive inputs → close to 1, Zero → exactly 0.5

Linear Output: [3.67  4.523]
Activated Output: [0.975 0.989]


##### Step 6. Output Results

In [7]:
print("Input Vector:")
print(input_vector)

print("\nWeights Matrix:")
print(weights_matrix)

print("\nBias Vector:")
print(bias_vector)

print("\nLinear Output (Before Activation):")
print(linear_output)

print("\nActivated Output (After Sigmoid):")
print(activated_output)

Input Vector:
[2 3 4]

Weights Matrix:
[[0.375 0.951]
 [0.732 0.599]
 [0.156 0.156]]

Bias Vector:
[0.1 0.2]

Linear Output (Before Activation):
[3.67  4.523]

Activated Output (After Sigmoid):
[0.975 0.989]
